### ISSUE TITLE
Issue installing TensorFlow on Mac OS 10.13.5

### ISSUE THREAD

**Issue by shabtastic** [duke-mlss/Duke-MLSS-2018#1]
Hi. I've been having trouble installing TensorFlow on my Mac (running 10.13.5 with Python 3.6.5 and conda 4.5.4 through miniconda3). (I previously tried to install using the official TensorFlow instructions and had no luck.) After successfully installing (as per your instructions in 00A), I get the following output when trying to verify:

```
mymac:~ me$ source activate tflow
(tflow) mymac:~ me$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2018-06-18 20:11:45.176727: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
```

Any idea why the output has the extra characters? Thanks!

**Comment by shabtastic** [comment]
I actually was asking about the extra characters in the 'Hello, TensorFlow!' output (i.e., the 'b' at the start and the single quotes):
`b'Hello, TensorFlow!'
Is that related to the CPU instructions? Sorry for any confusion. Thanks again!

**Comment by kevinjliang** [comment]
Ah. That's just Python saying it's a byte string (as opposed to Unicode). You can also ignore that!

https://stackoverflow.com/questions/40904979/the-print-of-string-constant-is-always-attached-with-b-intensorflow
https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal

**Comment by shabtastic** [comment]
Glad it's not anything to worry about! Good to know, and thanks again!
